[platformio]
default_envs = teensy32
src_dir = firmware/src
include_dir = firmware/include
lib_dir = firmware/lib
test_dir = firmware/test

[env:teensy32]
platform = teensy
board = teensy31
framework = arduino
monitor_speed = 115200
build_flags =
    -std=gnu++17
    -Wall
    -Wextra
lib_deps =
    fastled/FastLED @ ^3.6.0

[env:teensy32_led_test]
extends = env:teensy32
build_src_filter =
    -<*>
    +<../examples/basic_led_test>
