############################################################
# Entertainment Zone Automations
############################################################

automation:
  - id: "1763510190108"
    alias: If EA turns off > turn back on
    description: "If this specific switch is turned off, wait 45 seconds and turn it back on."
    trigger:
      - platform: device
        type: turned_off
        device_id: c7b80a710623b79eb56fb77bcf2c4e25
        entity_id: 64a8c7df8be49914f234d465cca7b90a
        domain: switch
    condition: []
    action:
      - delay:
          hours: 0
          minutes: 0
          seconds: 45
          milliseconds: 0
      - device_id: c7b80a710623b79eb56fb77bcf2c4e25
        domain: switch
        entity_id: 64a8c7df8be49914f234d465cca7b90a
        type: turn_on
    mode: single
